name: Extension Test

on:
  push:
    branches:
      - main
      - "release/v*.*.*"
  pull_request:
    branches: [main]
    paths:
      - "extension/**"

jobs:
  eslint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: "extension/pnpm-lock.yaml"
      - run: pnpm install
        working-directory: extension
      - name: Run eslint check
        run: pnpm lint
        working-directory: extension

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: "extension/pnpm-lock.yaml"
      - run: pnpm install
        working-directory: extension
      - name: Run extension build
        run: pnpm build
        working-directory: extension

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: "extension/pnpm-lock.yaml"
      - run: pnpm install
        working-directory: extension
      - name: Run extension package
        run: pnpm package
        working-directory: extension
